server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///travel?serverTimezone=UTC
    username: root
    password: hello666
  main:
    allow-circular-references: true # 允许循环依赖，临时解决启动问题
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

logging:
  pattern:
    console: '%d{HH:mm:ss.sss} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'

mail:
  user: 3113942885@qq.com
  password: frgzgkxjpzrvdhfh
  host: smtp.qq.com # SMTP主机
  port: 587 # 端口（QQ邮箱推荐587）

project:
  path: http://localhost